-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        dim_inactive = true,
    },
})

-- Monitors
hl.monitor({
    output = "DP-1",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "-200x-1080",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.02Hz",
    position = "0x0",
    scale = 1.2,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("uwsm app -- zen-browser"))
